{{- if and .Values.toolServer.enabled .Values.toolServer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opscopilot.serviceAccountName" . }}
  namespace: {{ include "opscopilot.namespace" . }}
  labels:
    {{- include "opscopilot.labels" . | nindent 4 }}
    app.kubernetes.io/component: tool-server
{{- end }}
