global:
  namespaceOverride: ""

image:
  repository: "registry.k8s.io/external-dns/external-dns"
  tag: "v0.14.2"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""
  annotations: {}

provider:
  name: aws
  domainFilters: []
  zoneType: public

sources:
  ingress: true

registry:
  type: txt
  txtOwnerId: "opscopilot"
  txtPrefix: "external-dns-"

policy: upsert-only
interval: "1m"
logLevel: info
logFormat: json

env: []

resources: {}

terraform:
  outputContractVersion: ""
  dnsContract:
    route53_hosted_zone_id: ""
