apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "externaldns.fullname" . }}
  labels:
    {{- include "externaldns.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "externaldns.fullname" . }}
  labels:
    {{- include "externaldns.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "externaldns.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "externaldns.serviceAccountName" . }}
    namespace: {{ include "externaldns.namespace" . }}
